
###########################################################
######---------- ~/.config/kitty/kitty.conf ----------#####
###########################################################
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#---------------------------------------------------------#
#-------------------------------###########################
######################################
#####---------- Theme ----------#####
#####################################

background_opacity 0.85
dynamic_background_opacity yes
macos_option_as_alt yes

###########################
##### Fonts ----------#####
###########################

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

##############################################
#####---------- Colors palette ----------#####
##############################################

# Red
color1  #ff5555 
color9  #ff6e6e

# Green
color2  #50fa7b
color10 #69ff94

# Blue
color4  #8be9fd
color12 #a4ffff

# Cyan
color6  #8be9fd
color14 #a4ffff

# White
color7  #f8f8f2
color15 #ffffff

###----- Other colors -----###

# Magenta
#color5  #ff79c6
#color13 #ff92df

# Yellow
#color3  #f1fa8c
#color11 #ffffa5

# Black
#color0  #1a1a1a 
#color8  #3d3d3d 
